// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteTask(arg1:number):Promise<void>;

export function GetTasks():Promise<Array<models.Task>>;

export function InsertTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateTask(arg1:number,arg2:string,arg3:string):Promise<void>;
