// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTask(arg1) {
  return window['go']['backend']['App']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['backend']['App']['GetTasks']();
}

export function InsertTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['InsertTask'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UpdateTask'](arg1, arg2, arg3);
}
